<div style="background-color: #e6f2ff; padding: 15px; border-radius: 10px;">

# Session 2 — NumPy and Pandas for Data Analysis

## What will we learn?

In this session, we will learn how to:

- Work with numerical data using NumPy  
- Work with tabular (spreadsheet-like) data using Pandas  
- Clean and transform messy real-world data (data wrangling)  
- Compute descriptive statistics to summarize social science data  

These are foundational skills for analyzing survey data, experimental results, and observational datasets.

---

## Why does this matter in social sciences?

In social science research, data rarely comes clean and ready to analyze. You might work with:

- Survey responses  
- Behavioral experiment data  
- Administrative or demographic datasets  

Before answering research questions, you need to:

1. Clean the data  
2. Organize it  
3. Summarize it  

This is exactly what NumPy and Pandas help you do.

</div>


<div style="background-color: #e6f2ff; padding: 15px; border-radius: 10px; border-left: 5px solid #4a90e2;">

## Introduction to NumPy

NumPy (Numerical Python) is a library used for working with numbers efficiently.

It is especially useful for:

- Performing calculations on large datasets  
- Computing statistics  
- Handling numerical arrays  



Numpy allows you to work with **arrays with objects all of the same type** (all int, or all bool, etc.).

So you can do computations very efficiently without having to use loops. 

</div>

## Creating a numpy.ndarray

The basic data type of numpy is an **ndarray**.

ndarray = **N-dimensional array.**

A simple way to create an ndarray is np.arange (“a range”).

In [2]:
import numpy as np

# Works similar to range(N)
np.arange(1, 4)

## step size = 2
np.arange(1, 4, step = 2)

array([1, 2, 3])

<div style="background-color: #eaf7ea; padding: 15px; border-radius: 10px; border-left: 5px solid #4caf50;">

## 📝 Try It Yourself

How would you create an array ranging from 1 to 100, incrementing with a step size of .5? 

How long would this array be?

In [ ]:
#your code here

You can also create an ndarray by passing a list into the np.array(...) function.

```python
list_1 = [1, 2, 3, 4]
np_array = np.array(list_1)
print(type(np_array))

### Descriptive Statistics with NumPy

We often want to summarize data using:
- Mean (average)
- Standard deviation (spread)
- Sum (total)

In [5]:
# Imagine these are responses to a Likert-scale question (1–5)
responses = np.array([1, 2, 3, 4, 5, 3, 4, 2, 1, 5])
responses

responses.sum()   # Total sum
responses.mean()  # Average
responses.std()   # Standard deviation
responses.min()   # Minimum
responses.max()   # Maximum

np.int64(5)

In [4]:
a = np.array([2, 4, 5])
b = np.array([2, 2, 3])
a * b

array([ 4,  8, 15])

In [ ]:
#try applying other operations using arrays a and b

## Creating random arrays wit Numpy

`numpy.random.rand`(d1, ...) can be used to initialize an array with random numbers and dimensionality (d1, ...).

```python
Example:

## Generates a 1-D vector with 10 elements
np.random.rand(10)

## Generates a 2-D vector with shape (2, 2)
np.random.rand(2, 2)

 <div style="background-color: #e6f2ff; padding: 15px; border-radius: 10px; border-left: 5px solid #4a90e2;">

# Introduction to Pandas

**Pandas** is used for working with tabular data (like Excel or CSV files).

It allows you to:
- Organize data into rows and columns
- Filter and select data
- Compute statistics easily

The main structure is called a **DataFrame**.

</div>

In [6]:

import pandas as pd

### Creating a DataFrame (Example: student dataset)

In [7]:
data = {
    "age": [18, 19, 20, 21, 22],
    "study_hours": [2, 3, 5, 4, 6],
    "score": [70, 75, 85, 80, 90]
}

df = pd.DataFrame(data)
df

   age  study_hours  score
0   18            2     70
1   19            3     75
2   20            5     85
3   21            4     80
4   22            6     90

### Exploring the Data

We can quickly summarize the dataset:

In [9]:
df.describe()

             age  study_hours      score
count   5.000000     5.000000   5.000000
mean   20.000000     4.000000  80.000000
std     1.581139     1.581139   7.905694
min    18.000000     2.000000  70.000000
25%    19.000000     3.000000  75.000000
50%    20.000000     4.000000  80.000000
75%    21.000000     5.000000  85.000000
max    22.000000     6.000000  90.000000

### Selecting Data

We often want to focus on a specific variable:

In [10]:
df['study_hours']

0    2
1    3
2    5
3    4
4    6
Name: study_hours, dtype: int64

### Filtering Data

Example: students who studied more than 3 hours

In [ ]:
df[df['study_hours'] > 3]

### Why this matters

In social science research, you might:
- Filter participants based on conditions
- Compare subgroups
- Explore relationships between variables

## Data Wrangling (Cleaning Data)

Real-world data is messy. You will often encounter:
- Missing values
- Incomplete responses

Pandas provides tools to handle this.

In [11]:
df2 = pd.DataFrame({
    "age": [18, None, 20, 21],
    "score": [70, 75, None, 80]
})

df2

    age  score
0  18.0   70.0
1   NaN   75.0
2  20.0    NaN
3  21.0   80.0

### Sorting
Use `sort_values`.

In [15]:
df.sort_values("age", ascending=False)

   age  study_hours  score
4   22            6     90
3   21            4     80
2   20            5     85
1   19            3     75
0   18            2     70

### Groupby and Aggregation
Summarize by groups. Why isn't the example below a good option for grouping?

In [16]:
df.groupby("score")["age"].mean()

score
70    18.0
75    19.0
80    21.0
85    20.0
90    22.0
Name: age, dtype: float64

### Dropping Missing Values

In [12]:
df2.dropna()

    age  score
0  18.0   70.0
3  21.0   80.0

### Filling Missing Values

In [13]:
df2.fillna(df2.mean(numeric_only=True))

         age  score
0  18.000000   70.0
1  19.666667   75.0
2  20.000000   75.0
3  21.000000   80.0

### Why this matters

Decisions about missing data can affect your results:
- Dropping data reduces sample size
- Filling data introduces assumptions

These are important research decisions.

In [24]:
# more useful methods

# Show all unique values present in the 'age' column
df2['age'].unique()

# Count how many distinct values exist in the 'age' column
df2['age'].nunique()

# Count how many times each unique value appears in the 'age' column
df2['age'].value_counts()

age
18.0    1
20.0    1
21.0    1
Name: count, dtype: int64

In [27]:
#Select from DataFrame using criteria from multiple columns
newdf = df2[(df2['age']>20) & (df2['age']==21)]

print(newdf)

    age  score
3  21.0   80.0

<div style="background-color: #eaf7ea; padding: 15px; border-radius: 10px; border-left: 5px solid #4caf50;">

## 📝 Try It Yourself

1. Run the cell below to generate a new dataset. 
2. Run descriptive analysis (mean, sd, sum) for the numerical columns.  
3. Group by major and get the GPA for each group. Which one has the higehst GPA? 
4. Filter for Bio majors with GPA above 3.5.

</div>

In [17]:
data = {
    "student": ["Amina", "Jordan", "Kai", "Priya", "Luis"],
    "major": ["Bio", "CS", "Math", "Econ", "Bio"],
    "gpa": [3.6, 3.9, 3.2, 3.7, None],
    "credits": [60, 75, 45, 90, 30]
}

df = pd.DataFrame(data)
df

  student major  gpa  credits
0   Amina   Bio  3.6       60
1  Jordan    CS  3.9       75
2     Kai  Math  3.2       45
3   Priya  Econ  3.7       90
4    Luis   Bio  NaN       30

In [ ]:
#your code here

## CSV

### CSV Input

In [ ]:
df = pd.read_csv('example')

### CSV Output

In [18]:
df.to_csv('example',index=False)